source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'iTextField_Example', :exclusive => true do
  pod 'iTextField', :path => '../'
end

target 'iTextField_Tests', :exclusive => true do
  pod 'iTextField', :path => '../'

  
end
